import React from "react";
import Head from "next/head";

export const Seo = ({ title }) => {
  return (
    <Head>
      <title> {title ? title : "Blog"} </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
