import Head from "next/head";

import { GridHome } from "../components/Layout/GridHome";
import { getPosts } from "../services";

export default function Index({ posts }) {
  return (
    <>
      <Head>
        <title>Bog | </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GridHome posts={posts} />
    </>
  );
}

export const getServerSideProps = async () => {
  const posts = await getPosts();
  return {
    props: { posts }, // will be passed to the page component as props
  };
};
